on:
  push

name: Test
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    - name: Create server
      run: doctl compute droplet create openvpn-action-$GITHUB_RUN_ID-$GITHUB_RUN_NUMBER --size s-1vcpu-1gb --image debian-10-x64 --region lon1 --enable-ipv6 --ssh-keys be:66:76:61:a8:71:93:aa:e3:19:ba:d8:0d:d2:2d:d4
    - name: Wait for server to be created
      run: sleep 60
    - name: Get server IP
      run: echo ::set-output name=server_ip::$(doctl compute droplet list -o json | jq -r '.[] | select(.name == "'openvpn-action-$GITHUB_RUN_ID-$GITHUB_RUN_NUMBER'").networks.v4 | .[0].ip_address')
      id: server_info
    - name: Setup remote server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ steps.server_info.outputs.server_ip }}
        username: root
        key: ${{ secrets.SSH_KEY }}
        script: 'set -x && apt-get update && apt-get install -y git'
    - name: Download repo and checkout current commit
      uses: appleboy/ssh-action@master
      with:
        host: ${{ steps.server_info.outputs.server_ip }}
        username: root
        key: ${{ secrets.SSH_KEY }}
        script: 'set -x && git clone https://github.com/angristan/openvpn-install.git && cd openvpn-install && git checkout $GITHUB_SHA'
    - name: Run openvpn-install.sh in headless mode
      uses: appleboy/ssh-action@master
      with:
        host: ${{ steps.server_info.outputs.server_ip }}
        username: root
        key: ${{ secrets.SSH_KEY }}
        script: 'set -x && AUTO_INSTALL=y bash -x ~/openvpn-install/openvpn-install.sh && ps aux | grep openvpn | grep -v grep > /dev/null 2>&1 && echo "Success: OpenVPN is running" && exit 1 || echo "Failure: OpenVPN is not running" && exit 1'
    - name: Delete server
      run: doctl compute droplet delete -f openvpn-action-$GITHUB_RUN_ID-$GITHUB_RUN_NUMBER
