on:
  push

name: Test
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    - name: Save DigitalOcean kubeconfig
      run: doctl compute droplet list
